dubbo:
  application:
    name: user-provider
    id: user-provider
  registry:
    address: nacos://127.0.0.1:8848
  protocols:
    dubbo:
      name: dubbo
      port: -1
      server: tomcat
    rest:
      name: rest
      port: 8888
      server: tomcat
spring:
  application:
    name: provider-demo
  main:
    allow-bean-definition-overriding: true
server:
  port: 8085


